branches:
  only:
    - dev

environment:
  access_token:
    secure: a2/axB9QeFPtz2P0Q1naSwbi8mHzkBpZy3oSTwoQXSboGO4JKFk2ADhSSV1ni/xc

install:
  - mkdir ..\Wyam
  - mkdir ..\Output
  # Fetch the latest version of Wyam 
  - "curl -s https://raw.githubusercontent.com/Wyamio/Wyam/master/RELEASE -o ..\\Wyam\\wyamversion.txt"
  - set /P WYAMVERSION=< ..\Wyam\wyamversion.txt
  - echo %WYAMVERSION%
  # Get and unzip the latest version of Wyam
  - ps: Start-FileDownload "https://github.com/Wyamio/Wyam/releases/download/$env:WYAMVERSION/Wyam-$env:WYAMVERSION.zip" -FileName "..\Wyam\Wyam.zip"
  - 7z x ..\Wyam\Wyam.zip -o..\Wyam -r

build_script:
  - ..\Wyam\Wyam.exe --output ..\Output

on_success:
  - del Input\Scripts\jquery-2.1.1-vsdoc.js
  - del Input\_._  # Not sure where this one is coming from, but it needs to be deleted before checkout
  # Switch branches to gh-pages, clean the folder, copy everything in from the Wyam output, and commit/push
  # See http://www.appveyor.com/docs/how-to/git-push for more info
  - git config --global credential.helper store
  - git config --global user.email "mez613@gmail.com"
  - git config --global user.name "Mordechai Zuber"
  - ps: Add-Content "$env:USERPROFILE\.git-credentials" "https://$($env:access_token):x-oauth-basic@github.com`n"
  - git checkout master
  - git rm -rf .
  - xcopy ..\Output . /E
  - git remote set-url origin https://github.com/M-Zuber/M-Zuber.github.io.git
  - git add -A
  - git commit -a -m "Commit from AppVeyor"
  - git push
