#---------------------------------#
#  Build Script                   #
#---------------------------------#
build_script:
  - ps: .\build.ps1 -Target "AppVeyor" -Experimental

#---------------------------------#
#        Branches to build        #
#---------------------------------#
branches:
  only:
    - dev

#---------------------------------#
#  Build Cache                    #
#---------------------------------#
cache:
- tools -> setup.cake